title: "pratica-dplyr" author: "Fernanda" format: html toc: true lang: es theme: solar editor: visual ---ption disables the printing of code (only output is displayed).

#Introducción

Este documento contiene algunos ejemplos de uso de las funciones del paquete dplyr de \[Tydyverse\] (https://www.tydyverse.org/)

#Carga de paquetes

```{r}
# | label: carga-paquetes
# | message: false 
# | warning: false 

library(tidyverse)
library(palmerpenguins)
library(knitr)

```

#Carga de datos

```{r}
#| label: carga-datos
#| message: false
#| warning: false

delitos_2023 <- read.csv("estadisticaspoliciales2023.csv")
```

#select

##Ejemplos 1

```{r}
#| label: select-01
#select(penguins, species, bill_length_mm, sex)

penguins |> 
  select(species, bill_length_mm, sex) |>
  head(10) |>
  kable()

```

##Ejemplo 2

```{r}
#| label: select-02
 
penguins |>
  select(
    especie = species,
    longitud_pico_mm = bill_length_mm,
    sex
  ) |>
  head(10) |>
  kable()
```

#filter()

##Ejemplo 1

```{r}
#| label: filter-01

penguins |>
  select(species, island, sex) |> 
  filter(species == "Adelie") |>
  filter(sex == "male") |>
  filter(island == "Torgersen") |>
  kable()
```

```{r}
delitos_2023 <- read_csv(
  "estadisticaspoliciales2023.csv",
  locale = locale(encoding = "WINDOWS-1252")
)
```

##Ejemplo 2 

```{r}
#| label: filter-02

#Delitos cometidos a vehículos en el  cantón de Montes de Oca
delitos_2023 |>
  select(Delito, SubDelito, Victima, SubVictima, Canton, Distrito)|>
  filter(Canton == "MONTES DE OCA") |>
    filter(Victima == "VEHICULO") |>
    kable()
```
  
##Ejemplo 3 

``` {r}
#| label: filter-03

#Asaltos cometidos en San Pedro de Montes de Oca
delitos_2023 |>
  select(Delito, SubDelito, Victima, SubVictima, Canton, Distrito) |>
  filter(Canton == "MONTES DE OCA") |>
  filter(Distrito == "SAN PEDRO" ) |>
  filter(Delito == "ASALTO") |>
  filter(Delito == "HOMICIDIO") |>
  kable()
```

